### ISSUE TITLE
When sending dmx.render() it sends but resets after it

### ISSUE THREAD

**Issue by ZillionPrey** [andypotato/node-opendmx#1]
Hi.

I have successfully installed the driver on a raspberry pi 4 and also got the lib to work. My only problem now is if I set a channel value and send dmx.render() after it, it sets the value but then goes back to zero on every channel.

Hope someone can help me with that Issue.

**Comment by andypotato** [comment]
Depending on your DMX equipment you need to resend the universe data at regular intervals. This is usually handled automatically by your DMX controller, however once the process hosting the serial connection to the controller quits it may or may not stop doing so.

Try keeping your process alive and see if it helps.

**Comment by ZillionPrey** [comment]
Solution was to send the dmx values in an Interval like mentioned above.
